name: Plugin JSON Birleştirici

on:
  schedule:
    - cron: '0 */4 * * *'  # 4 saatte bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Requests modülünü yükle
        run: pip install requests

      - name: plugin_cache.json dosyasını cache’le
        uses: actions/cache@v4
        with:
          path: plugin_cache.json
          key: plugin-cache

      - name: JSON'ları birleştir
        run: python birlestir_plugins_json.py

      - name: Değişiklikleri pushla
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add birlesik_plugins.json plugin_cache.json
          git commit -m "🔄 JSON güncellendi ($(date))" || echo "Değişiklik yok"
          git push "https://${{ secrets.GH_PAT }}@github.com/mooncrown04/jsonbirlestir.git" HEAD:main
